title: Your awesome title
author: RJMorriss
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The domain of the 49% interesting reviewer

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
